# Generated by Django 4.2.13 on 2024-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpg", upload_to="avatars/"
            ),
        ),
    ]
