# Generated by Django 4.2.13 on 2024-06-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="emial",
        ),
    ]
