# Generated by Django 4.2.13 on 2024-05-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="Platform",
            field=models.CharField(
                choices=[
                    ("PC", "PC."),
                    ("PLAYSTATION", "PLAYSTATION."),
                    ("XBOX", "XBOX."),
                    ("NINTENDO", "NINTENDO."),
                ],
                default="PC",
                max_length=50,
            ),
        ),
    ]
