# Generated by Django 4.2.13 on 2024-05-29 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0003_alter_article_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.ForeignKey(
                default="moderator",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
