# Generated by Django 4.2.13 on 2024-05-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0009_alter_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="Author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Blog.author"
            ),
        ),
    ]
