# Generated by Django 4.2.13 on 2024-05-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0011_alter_author_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="Author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="Date_Posted",
            new_name="date_posted",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="Picture",
            new_name="picture",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="Platform",
            new_name="platform",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="SubTitle",
            new_name="subTitle",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="Title",
            new_name="title",
        ),
    ]
