# Generated by Django 4.2.13 on 2024-05-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0012_rename_author_article_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="subTitle",
            new_name="subtitle",
        ),
    ]
