# Generated by Django 4.2.13 on 2024-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0013_rename_subtitle_article_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="picture",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
