# Generated by Django 4.2.13 on 2024-05-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0014_alter_article_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
