# Generated by Django 4.2.13 on 2024-05-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0015_alter_article_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="article",
            name="platform",
        ),
        migrations.AlterField(
            model_name="article",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="media/images"),
        ),
        migrations.AddField(
            model_name="article",
            name="platforms",
            field=models.ManyToManyField(to="Blog.platform"),
        ),
    ]
