# Generated by Django 4.2.13 on 2024-05-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0016_platform_remove_article_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.CharField(
                choices=[
                    ("NEWS", "NEWS"),
                    ("LATEST", "LATEST"),
                    ("REVIEWS", "REVIEWS"),
                    ("RATING", "RATING"),
                    ("GUIDE", "GUIDE"),
                ],
                default="NEWS",
                max_length=20,
            ),
        ),
    ]
