# Generated by Django 4.2.13 on 2024-06-02 17:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0017_article_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
