# Generated by Django 4.2.13 on 2024-06-02 10:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0018_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
