# Generated by Django 4.2.13 on 2024-06-11 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0021_alter_comment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.ForeignKey(
                limit_choices_to={"status": "moderator"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
