# Generated by Django 4.2.13 on 2024-06-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0025_alter_reply_date_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
