# Generated by Django 4.2.13 on 2024-06-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0026_alter_comment_options_alter_comment_date_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["-date_added"]},
        ),
    ]
