# Generated by Django 4.2.13 on 2024-06-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0027_alter_reply_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-date_posted"]},
        ),
    ]
