# Generated by Django 4.2.13 on 2024-06-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0029_comment_parent_alter_comment_id_delete_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(),
        ),
    ]
