# Generated by Django 4.2.13 on 2024-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0031_rename_body_comment_comment_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AlterField(
            model_name="article",
            name="tag",
            field=models.CharField(
                choices=[
                    ("NEWS", "NEWS"),
                    ("LATEST", "LATEST"),
                    ("REVIEWS", "REVIEWS"),
                    ("GUIDE", "GUIDE"),
                ],
                default="NEWS",
                max_length=20,
            ),
        ),
    ]
