# Generated by Django 4.2.13 on 2024-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0032_game_alter_reply_options_alter_article_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="developer",
            field=models.CharField(default="studio", max_length=300),
        ),
        migrations.AddField(
            model_name="game",
            name="genre",
            field=models.CharField(default="free to play", max_length=300),
        ),
        migrations.AddField(
            model_name="game",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="media/images"),
        ),
    ]
