# Generated by Django 4.2.13 on 2024-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0033_game_developer_game_genre_game_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.CharField(max_length=300),
        ),
    ]
