# Generated by Django 4.2.13 on 2024-06-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0034_alter_game_developer_alter_game_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
