# Generated by Django 4.2.13 on 2024-06-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0037_alter_article_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["release_date"]},
        ),
    ]
