# Generated by Django 4.2.13 on 2024-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0038_alter_game_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateTimeField(),
        ),
    ]
