# Generated by Django 4.2.13 on 2024-06-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0039_alter_game_release_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
