# Generated by Django 4.2.13 on 2024-06-23 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0040_delete_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Enter rating from 1 to 5",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
